# Generated by Django 2.2 on 2020-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
