# Generated by Django 2.2 on 2020-08-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200823_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
